In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_excel('HousePricePrediction.xlsx')
df

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2914,160,RM,1936,Inside,Twnhs,7,1970,1970,CemntBd,0.0,546.0,NaN
2915,2915,160,RM,1894,Inside,TwnhsE,5,1970,1970,CemntBd,0.0,546.0,NaN
2916,2916,20,RL,20000,Inside,1Fam,7,1960,1996,VinylSd,0.0,1224.0,NaN
2917,2917,85,RL,10441,Inside,1Fam,5,1992,1992,HdBoard,0.0,912.0,NaN
2918,2918,60,RL,9627,Inside,1Fam,5,1993,1994,HdBoard,0.0,996.0,NaN

In [4]:
df.head(100)

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,60,RL,9765,Corner,1Fam,8,1993,1993,VinylSd,0.0,680.0,185000.0
96,96,20,RL,10264,Inside,1Fam,5,1999,1999,VinylSd,0.0,1588.0,214000.0
97,97,20,RL,10921,Inside,1Fam,5,1965,1965,HdBoard,0.0,960.0,94750.0
98,98,30,RL,10625,Corner,1Fam,5,1920,1950,Wd Sdng,0.0,458.0,83000.0
99,99,20,RL,9320,Inside,1Fam,5,1959,1959,Plywood,0.0,950.0,128950.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            2919 non-null   int64
 1   MSSubClass    2919 non-null   int64
 2   MSZoning      2915 non-null   object
 3   LotArea       2919 non-null   int64
 4   LotConfig     2919 non-null   object
 5   BldgType      2919 non-null   object
 6   OverallCond   2919 non-null   int64
 7   YearBuilt     2919 non-null   int64
 8   YearRemodAdd  2919 non-null   int64
 9   Exterior1st   2918 non-null   object
 10  BsmtFinSF2    2918 non-null   float64
 11  TotalBsmtSF   2918 non-null   float64
 12  SalePrice     1460 non-null   float64
dtypes: float64(3), int64(6), object(4)
memory usage: 296.6+ KB

In [8]:
cat = []
con = []

for i in df.columns:
    if df[i].dtype == 'object':
        cat.append(i)
    else:
        con.append(i)

print("Categorical: ", cat, "\n Numerical: ", con)

Categorical:  ['MSZoning', 'LotConfig', 'BldgType', 'Exterior1st']
 Numerical:  ['Id', 'MSSubClass', 'LotArea', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'BsmtFinSF2', 'TotalBsmtSF', 'SalePrice']

In [9]:

def get_column_insights(df, target='SalePrice'):
    
    insights = []

    cat_cols = df.select_dtypes(include=['object']).columns
    num_cols = df.select_dtypes(include=['int64', 'float64']).columns
    date_cols = df.select_dtypes(include=['datetime64']).columns

    for col in df.columns:
        if col == target:
            continue

        if col in cat_cols:
            col_type = "Categorical"
        elif col in date_cols:
            col_type = "Temporal"
        else:
            col_type = "Numerical"
        
        if col_type == "Numerical":
            correlation = df[[col, target]].corr().iloc[0, 1]
            impact = (
                "High" if abs(correlation) > 0.5 else
                "Medium" if abs(correlation) > 0.2 else
                "Low"
            )
        else:
            correlation = "N/A"
            impact = "Depends on category influence"

        insights.append({
            "Column": col,
            "Type": col_type,
            "Correlation_with_Price": correlation,
            "Impact_Level": impact
        })

    return pd.DataFrame(insights)


insight_df = get_column_insights(df)
print(insight_df)

          Column         Type Correlation_with_Price  \
0             Id    Numerical              -0.021917
1     MSSubClass    Numerical              -0.084284
2       MSZoning  Categorical                    N/A
3        LotArea    Numerical               0.263843
4      LotConfig  Categorical                    N/A
5       BldgType  Categorical                    N/A
6    OverallCond    Numerical              -0.077856
7      YearBuilt    Numerical               0.522897
8   YearRemodAdd    Numerical               0.507101
9    Exterior1st  Categorical                    N/A
10    BsmtFinSF2    Numerical              -0.011378
11   TotalBsmtSF    Numerical               0.613581

                     Impact_Level
0                             Low
1                             Low
2   Depends on category influence
3                          Medium
4   Depends on category influence
5   Depends on category influence
6                             Low
7                            High
8                            High
9   Depends on category influence
10                            Low
11                           High